apiVersion: v1
kind: Service
metadata:
  name: borisaelen-django
  labels:
    app: borisaelen
spec:
  ports:
    - port: 8000
      name: "website"
  type: LoadBalancer
  selector:
    app: borisaelen
    tier: frontend
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: borisaelen-django
  labels:
    app: borisaelen
spec:
  selector:
    matchLabels:
      app: borisaelen
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: borisaelen
        tier: frontend
    spec:
      serviceAccountName: borisaelen-sa
      containers:
      - name: borisaelen
        image: borisaelen-website
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: borisaelen-web
        env:
        - name: DJANGO_DATABASE
          value: "vault"
        - name: VAULT_URL
          value: "http://vault:8200"
        - name: VAULT_DATABASE_PATH
          value: database/static-creds/django-admin
        - name: VAULT_KUBERNETES_ROLE
          value: "borisaelen"
        - name: VAULT_KUBERNETES_TOKEN_PATH
          value: /run/secrets/kubernetes.io/serviceaccount/token
        - name: DATABASE_URL
          value: "mysql://borisaelen-mysql:3306/borisaelen"
        - name: VAULT_DEBUG
          value: "yes"
        # livenessProbe:
        #   httpGet:
        #     path: /blog/
        #     port: 8000
        #   failureThreshold: 30
        #   initialDelaySeconds: 3
        #   periodSeconds: 3