apiVersion: v1
kind: Service
metadata:
  name: borisaelen-mysql
  labels:
    app: borisaelen
spec:
  ports:
    - port: 3306
      nodePort: 30306
  type: NodePort
  selector:
    app: borisaelen
    tier: mysql
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: borisaelen-sa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: borisaelen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M  
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: borisaelen-mysql
  labels:
    app: borisaelen
spec:
  selector:
    matchLabels:
      app: borisaelen
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: borisaelen
        tier: mysql
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "borisaelen"
        vault.hashicorp.com/agent-inject-secret-mysql_rootpw: 'secret/borisaelen-website/database'
        vault.hashicorp.com/agent-inject-template-mysql_rootpw: | 
            {{- with secret "secret/borisaelen-website/database" -}}
            {{ .Data.data.mysql_rootpw }}
            {{- end }}
    spec:
      serviceAccountName: borisaelen-sa
      containers:
      - image: mysql:8.0.11
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: /vault/secrets/mysql_rootpw
        - name: innodb_buffer_pool_size
          value: "134217728"
        resources:  
          limits:
            memory: "512Mi"
          requests:
            memory: "128Mi"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
